language: java
jdk:
- oraclejdk8
after_success:
- ".buildscript/deploy_snapshot.sh"
env:
  global:
  - secure: cjr3e54tNXnf12uf8RlWVWMP/J/Uu4u/YH9r3fwNc9GrYISYfcCdo8UVqQRjBbOYBleabINo9gvMMPKrGprwtVNIYFaxuBbwOWWz9bdUt0dLBdqe5RC9vUzW0T0CQC4V5p7z/TM/cpquIlVqOUSBFWpIFDgAulSVSXWAzQmgh0PNRMyqzHS2FN2u62LTkhVuLEJPgkZW3auYXebuHZ3+hwoJzr3Re9cvLBpEhkwImwd1MLTRZOVeY7Rygjxjgs5x7deNPXZQPq/dSDq3UdcxGAzCRb6/COiiHNhpTH17l5wexC3QtpSROOjVrthR7pz5xZ45i8Yx9di7bdNBoI1YE8HwAyuIxzlD91BshFlxNbfFRGa66UQ6bs/ktGUgACc9BIo7VKI28ECu8FF9DNvxG9sfzjAQmG2IERMvvGtG01nRgbPsCN4EikpHOD2NIlevSnY4uOh73gzKpVt/doB1TXz9ZRgLaXYI1IZNK+ezUqjZn/nS0wJ9DZBes9JquY5xFiudsZJ4NFr9FqvHV1xoMSWb0TXBaOEmffdtksf/Xsmeev8/jj4XlxadTbsHCZhbtH9s3Im5cZ1n3hDYmTffd0jnYzd49ExqNS3aqD77opDUnZDpq2j+UurSTgSp4frZkYUt9IpGzvsYY9g07vBYGD4weGc+ZqfCFpyBvqFkAAM=
  - secure: CSo8oKm+ZRiyWxn93eSjm+STN1L5udvUxnnWYMoUbYlISGPXEVmUydwgLu7K9JG4o6W/0C+OHIllBMDSq0DGDjMGdGzed8Sh6IVRkxkUoDd2xBAxBnbgkO8SGTes1CL+9PqMBeKcZBgOBpGMSAKVjjUISvTn/S9Ze6pMO+PVgk60gVzQELCDhCz/1PQNLUSxMwZu8B9QI6AuJPFHV+q/lGSPEJRK2XMHl4qCRC/u99pFOSrXgLQlVrhKeaBGa7ioNDWMpMEFLUvc1b4Y/oChx/wu07fGOBWjiweIyDl42Me2tuBg5iy0fHDzFAyqNMr2+DDnLXUT7qViBLLPOOoOzGCCGiQ7wEGgsoatct3YG8aARKMRAd32Q0nEW4vwnBZuILkHhLdwzv9G+lhHZs9RAv5zYR4p3lEiOuksUG9+awW8YYoj6eMJofz+tkKe4L9V7ktSJdqHkvecI/RecnEDUcm+5znuywRHWsDTyzDv0+yS3o8yY2QBfNiv2pCmLN8b+vOstn1p/OVG0bD9wSWDDf/fKCRyfNXRuWN7feZuJYlqOj4a4XNoD333wJjCmDfFjVPfSAHL0fLHuFQ18heQbW2Qgrkt1zKfioQ0+gXtgRffJRPMFLVDMqAlpsZU/1+GPkr+wH7GhfhTfvhknZ1Ovs6Fk5mCnehnc/LD73cY+ZI=
notifications:
  email: false
sudo: false
cache:
  directories:
  - "$HOME/.gradle"
